"""Nifty 100 ticker universe (yfinance .NS format).
Start small to test; expand to full NSE later by swapping this list
for the NSE EQUITY_L.csv download (see fetch.py notes).
"""
NIFTY_100 = [
    "RELIANCE","TCS","HDFCBANK","ICICIBANK","INFY","HINDUNILVR","ITC","SBIN",
    "BHARTIARTL","BAJFINANCE","KOTAKBANK","LT","HCLTECH","AXISBANK","MARUTI",
    "ASIANPAINT","SUNPHARMA","TITAN","ULTRACEMCO","WIPRO","NESTLEIND","ONGC",
    "NTPC","POWERGRID","M&M","TATAMOTORS","TATASTEEL","ADANIENT","ADANIPORTS",
    "COALINDIA","BAJAJFINSV","JSWSTEEL","GRASIM","HDFCLIFE","SBILIFE","BRITANNIA",
    "DRREDDY","CIPLA","EICHERMOT","TECHM","INDUSINDBK","DIVISLAB","BPCL","HEROMOTOCO",
    "HINDALCO","APOLLOHOSP","TATACONSUM","BAJAJ-AUTO","UPL","LTIM","DABUR","GAIL",
    "GODREJCP","HAVELLS","DLF","SIEMENS","PIDILITIND","AMBUJACEM","BANKBARODA",
    "SHREECEM","ICICIPRULI","BAJAJHLDNG","MARICO","BERGEPAINT","INDIGO","TORNTPHARM",
    "COLPAL","PNB","ADANIGREEN","VEDL","BOSCHLTD","MCDOWELL-N","IOC","CANBK",
    "CHOLAFIN","NAUKRI","MOTHERSON","SRF","BEL","LODHA","TVSMOTOR","ZOMATO",
    "TRENT","ADANIPOWER","IRCTC","JINDALSTEL","HDFCAMC","ICICIGI","MUTHOOTFIN",
    "PIIND","AUBANK","DMART","SBICARD","GICRE","INDUSTOWER","NMDC","TATAPOWER",
    "PGHH","ABBOTINDIA","BANKINDIA","ZYDUSLIFE",
]
